from __future__ import annotations

from shared_types.exploration import NpcAttitude
from shared_types.social import (
    MagicalNormTag,
    NormProfile,
    NormScope,
    SocialImmediateReaction,
    SocialIncidentCategory,
    SocialIncidentSeverity,
    SocialPropagationKind,
    WitnessReactionCategory,
)
from shared_types.social_content import (
    CampaignSocialContentPack,
    FactionAuthorityTemplate,
    IncidentConsequenceTemplate,
    LocationSocialBinding,
    NpcSocialTemplate,
    PropagationChainTemplate,
    SceneSocialBinding,
    WitnessArchetypeTemplate,
    WitnessTendencyProfile,
)


def build_campaign_social_content_pack(*, campaign_id: str) -> CampaignSocialContentPack:
    if campaign_id == 'lmop':
        return build_lmop_social_content_pack()
    raise ValueError(f'Unsupported social content pack for campaign {campaign_id!r}.')


def build_lmop_social_content_pack() -> CampaignSocialContentPack:
    witness_archetypes = {
        'tavern_patron': WitnessArchetypeTemplate(
            archetype_id='tavern_patron',
            label='Tavern patron',
            tendencies=WitnessTendencyProfile(call_authority=1, threat_sensitivity=2, rumor_spread=2, suspicious_casting_misinterpretation=1, courage=0, stranger_trust=0, authority_respect=1),
            description='Likely to gossip, watch for trouble, and call for help rather than intervene alone.',
        ),
        'barkeep': WitnessArchetypeTemplate(
            archetype_id='barkeep',
            label='Barkeep',
            tendencies=WitnessTendencyProfile(intervene_directly=1, call_authority=3, public_magic_tolerance=0, threat_sensitivity=3, rumor_spread=2, courage=1, authority_respect=2),
            description='Protective of property and likely to bring in authorities when the room turns ugly.',
        ),
        'merchant': WitnessArchetypeTemplate(
            archetype_id='merchant',
            label='Merchant or employer',
            tendencies=WitnessTendencyProfile(call_authority=2, threat_sensitivity=2, rumor_spread=1, suspicious_casting_misinterpretation=1, stranger_trust=0, authority_respect=1),
            description='Values orderly bargains and remembers coercion, theft, or public threats.',
        ),
        'guard': WitnessArchetypeTemplate(
            archetype_id='guard',
            label='Guard',
            tendencies=WitnessTendencyProfile(intervene_directly=2, call_authority=3, public_magic_tolerance=-1, threat_sensitivity=3, courage=2, authority_respect=3),
            description='Watches for breaches of order and is ready to escalate to formal authority.',
            report_to_faction_ids=('waterdeep-watch',),
        ),
        'watch_officer': WitnessArchetypeTemplate(
            archetype_id='watch_officer',
            label='Watch officer',
            tendencies=WitnessTendencyProfile(intervene_directly=2, call_authority=3, public_magic_tolerance=-1, threat_sensitivity=3, rumor_spread=0, courage=2, authority_respect=3),
            description='Interprets public disorder through a legal and civic-order lens.',
            report_to_faction_ids=('waterdeep-watch', 'lords-alliance'),
        ),
        'noble_servant': WitnessArchetypeTemplate(
            archetype_id='noble_servant',
            label='Noble servant',
            tendencies=WitnessTendencyProfile(call_authority=2, public_magic_tolerance=-1, threat_sensitivity=2, rumor_spread=1, authority_respect=3),
            description='Sensitive to decorum and more likely to summon someone above them than intervene.',
        ),
        'priest_temple_official': WitnessArchetypeTemplate(
            archetype_id='priest_temple_official',
            label='Priest or temple official',
            tendencies=WitnessTendencyProfile(intervene_directly=1, call_authority=1, public_magic_tolerance=1, threat_sensitivity=2, rumor_spread=1, authority_respect=2),
            description='Favors sanctioned aid but reacts strongly to taboo or coercive magic.',
        ),
        'traveler': WitnessArchetypeTemplate(
            archetype_id='traveler',
            label='Traveler',
            tendencies=WitnessTendencyProfile(call_authority=0, public_magic_tolerance=1, threat_sensitivity=2, rumor_spread=1, courage=0),
            description='Pragmatic witness who mostly cares whether magic or violence threatens safety.',
        ),
        'miner_laborer': WitnessArchetypeTemplate(
            archetype_id='miner_laborer',
            label='Miner or laborer',
            tendencies=WitnessTendencyProfile(intervene_directly=1, public_magic_tolerance=0, threat_sensitivity=2, rumor_spread=2, courage=1),
            description='Values practical help and resents threats or broken bargains.',
        ),
        'criminal_informant': WitnessArchetypeTemplate(
            archetype_id='criminal_informant',
            label='Criminal or informant',
            tendencies=WitnessTendencyProfile(intervene_directly=-1, call_authority=-2, public_magic_tolerance=1, threat_sensitivity=1, rumor_spread=2, suspicious_casting_misinterpretation=2),
            description='Reads danger quickly and may spread information for leverage rather than law.',
        ),
        'common_townsfolk': WitnessArchetypeTemplate(
            archetype_id='common_townsfolk',
            label='Common townsfolk',
            tendencies=WitnessTendencyProfile(call_authority=1, public_magic_tolerance=0, threat_sensitivity=2, rumor_spread=2, suspicious_casting_misinterpretation=1),
            description='Generally nonconfrontational but quick to form a local impression.',
        ),
        'guild_member': WitnessArchetypeTemplate(
            archetype_id='guild_member',
            label='Guild member',
            tendencies=WitnessTendencyProfile(call_authority=1, threat_sensitivity=2, rumor_spread=1, courage=1, stranger_trust=0, authority_respect=2),
            description='Values contracts, reputation, and orderly business conduct.',
        ),
    }
    faction_templates = {
        'waterdeep-watch': FactionAuthorityTemplate(
            template_id='waterdeep-watch',
            label='The Waterdeep Watch',
            cared_incident_categories=(
                SocialIncidentCategory.HOSTILE_SPELLCASTING,
                SocialIncidentCategory.VIOLENCE,
                SocialIncidentCategory.THREAT,
                SocialIncidentCategory.THEFT,
                SocialIncidentCategory.UNAUTHORIZED_MAGIC,
                SocialIncidentCategory.ENCHANTMENT_MAGIC_USED,
            ),
            default_social_tags=('legal-scrutiny', 'watch-alert'),
            preferred_immediate_reaction=SocialImmediateReaction.CALLS_AUTHORITY,
            response_delay_seconds=5 * 60,
            summary='Treats public magical disturbance and visible violence as public-order matters.',
        ),
        'lords-alliance': FactionAuthorityTemplate(
            template_id='lords-alliance',
            label="The Lords' Alliance",
            cared_incident_categories=(
                SocialIncidentCategory.HOSTILE_SPELLCASTING,
                SocialIncidentCategory.THREAT,
                SocialIncidentCategory.DECEPTION_EXPOSED,
                SocialIncidentCategory.CONTRACT_BROKEN,
            ),
            default_social_tags=('decorum-breach',),
            preferred_immediate_reaction=SocialImmediateReaction.WATCHES_CLOSELY,
            response_delay_seconds=15 * 60,
            summary='Prefers discipline and remembers breaches of decorum, coercion, and broken promises.',
        ),
        'rockseeker': FactionAuthorityTemplate(
            template_id='rockseeker',
            label='Rockseeker interests',
            cared_incident_categories=(
                SocialIncidentCategory.THREAT,
                SocialIncidentCategory.CONTRACT_BROKEN,
                SocialIncidentCategory.HOSTILE_SPELLCASTING,
                SocialIncidentCategory.AID_OR_HEALING,
                SocialIncidentCategory.PROMISE_KEPT,
            ),
            default_social_tags=('employer-memory',),
            preferred_immediate_reaction=SocialImmediateReaction.WATCHES_CLOSELY,
            response_delay_seconds=20 * 60,
            summary='Tracks whether the party protects Rockseeker business or becomes a liability.',
        ),
        'merchant-guild': FactionAuthorityTemplate(
            template_id='merchant-guild',
            label='Merchant guilds',
            cared_incident_categories=(SocialIncidentCategory.THEFT, SocialIncidentCategory.THREAT, SocialIncidentCategory.CONTRACT_BROKEN),
            default_social_tags=('service-refusal-risk',),
            preferred_immediate_reaction=SocialImmediateReaction.REFUSES_SERVICE,
            response_delay_seconds=30 * 60,
            summary='Cares about theft, unpaid obligations, and public threats against trade.',
        ),
        'town-council': FactionAuthorityTemplate(
            template_id='town-council',
            label='Town authorities',
            cared_incident_categories=(SocialIncidentCategory.VIOLENCE, SocialIncidentCategory.THREAT, SocialIncidentCategory.UNAUTHORIZED_MAGIC),
            default_social_tags=('civic-memory',),
            preferred_immediate_reaction=SocialImmediateReaction.REPORTS_LATER,
            response_delay_seconds=30 * 60,
            summary='Cares about order, trade stability, and who looks dangerous to the settlement.',
        ),
        'caravan-company': FactionAuthorityTemplate(
            template_id='caravan-company',
            label='Caravan companies',
            cared_incident_categories=(SocialIncidentCategory.THREAT, SocialIncidentCategory.TRESPASS, SocialIncidentCategory.CONTRACT_BROKEN),
            default_social_tags=('route-risk',),
            preferred_immediate_reaction=SocialImmediateReaction.WATCHES_CLOSELY,
            response_delay_seconds=20 * 60,
            summary='Pays attention to who is safe to hire or trust around goods and routes.',
        ),
    }
    npc_templates = {
        'gundren-rockseeker': NpcSocialTemplate(
            npc_id='gundren-rockseeker',
            label='Gundren Rockseeker',
            witness_archetype_id='merchant',
            faction_ids=('rockseeker',),
            baseline_attitude=NpcAttitude.FRIENDLY,
            respect_for_authority=1,
            tolerance_for_visible_magic=0,
            sensitivity_to_threats=3,
            reporting_tendency=1,
            rumor_tendency=1,
            remembers_aid=True,
            remembers_deceit=True,
            remembers_charm=True,
            unforgivable_incidents=(SocialIncidentCategory.THREAT, SocialIncidentCategory.HOSTILE_SPELLCASTING, SocialIncidentCategory.CONTRACT_BROKEN),
            special_tags=('employer', 'contract-principal'),
        ),
        'sildar-hallwinter': NpcSocialTemplate(
            npc_id='sildar-hallwinter',
            label='Sildar Hallwinter',
            witness_archetype_id='watch_officer',
            faction_ids=('lords-alliance', 'waterdeep-watch'),
            baseline_attitude=NpcAttitude.COOPERATIVE,
            respect_for_authority=3,
            tolerance_for_visible_magic=0,
            sensitivity_to_threats=3,
            reporting_tendency=3,
            rumor_tendency=0,
            remembers_aid=True,
            remembers_deceit=True,
            remembers_charm=True,
            unforgivable_incidents=(SocialIncidentCategory.ENCHANTMENT_MAGIC_USED, SocialIncidentCategory.HOSTILE_SPELLCASTING, SocialIncidentCategory.THREAT),
            special_tags=('lawful-witness', 'discipline-minded'),
        ),
    }
    norm_profiles = {
        'norm:scene:tavern-common-room': NormProfile(
            norm_id='norm:scene:tavern-common-room',
            applies_to_kind='scene',
            applies_to_id='tavern_common_room',
            label='Tavern common room',
            scope=NormScope.SCENE_OVERRIDE,
            tags=(MagicalNormTag.PUBLIC_ORDER_SENSITIVE, MagicalNormTag.ANTI_PUBLIC_THREATS),
            summary='Crowded common rooms are noisy but quick to react to threats, violence, or disruptive magic.',
            suspicious_magic_modifier=1,
            hostile_magic_modifier=2,
        ),
        'norm:scene:open-market': NormProfile(
            norm_id='norm:scene:open-market',
            applies_to_kind='scene',
            applies_to_id='open_market',
            label='Open market',
            scope=NormScope.SCENE_OVERRIDE,
            tags=(MagicalNormTag.PUBLIC_ORDER_SENSITIVE, MagicalNormTag.ANTI_PROPERTY_DAMAGE),
            summary='Markets punish disruption, theft, and damage more than visible but helpful magic.',
            suspicious_magic_modifier=1,
            hostile_magic_modifier=2,
        ),
        'norm:scene:roadside-inn': NormProfile(
            norm_id='norm:scene:roadside-inn',
            applies_to_kind='scene',
            applies_to_id='roadside_inn',
            label='Roadside inn',
            scope=NormScope.SCENE_OVERRIDE,
            tags=(MagicalNormTag.GUARDED_MAGIC, MagicalNormTag.PUBLIC_ORDER_SENSITIVE),
            summary='Travelers accept practical magic, but chaos in the common room spreads quickly.',
            suspicious_magic_modifier=1,
            hostile_magic_modifier=2,
        ),
        'norm:scene:wilderness-campsite': NormProfile(
            norm_id='norm:scene:wilderness-campsite',
            applies_to_kind='scene',
            applies_to_id='wilderness_campsite',
            label='Wilderness campsite',
            scope=NormScope.SCENE_OVERRIDE,
            tags=(MagicalNormTag.OPEN_MAGIC,),
            summary='Useful survival magic is accepted unless it endangers the group.',
            helpful_magic_modifier=-1,
        ),
        'norm:scene:city-guard-checkpoint': NormProfile(
            norm_id='norm:scene:city-guard-checkpoint',
            applies_to_kind='scene',
            applies_to_id='city_guard_checkpoint',
            label='City guard checkpoint',
            scope=NormScope.SCENE_OVERRIDE,
            tags=(MagicalNormTag.RESTRICTED_MAGIC, MagicalNormTag.PUBLIC_ORDER_SENSITIVE),
            summary='Visible coercive or unauthorized magic near guards draws immediate scrutiny.',
            suspicious_magic_modifier=2,
            hostile_magic_modifier=2,
        ),
        'norm:waterdeep-public-order': NormProfile(
            norm_id='norm:waterdeep-public-order',
            applies_to_kind='location',
            applies_to_id='waterdeep',
            label='Waterdeep public order',
            scope=NormScope.LOCATION,
            tags=(MagicalNormTag.GUARDED_MAGIC, MagicalNormTag.PUBLIC_ORDER_SENSITIVE),
            summary='Public spellcasting is tolerated until it becomes suspicious, disruptive, or coercive.',
            suspicious_magic_modifier=1,
            hostile_magic_modifier=2,
        ),
        'norm:waterdeep-anti-enchantment': NormProfile(
            norm_id='norm:waterdeep-anti-enchantment',
            applies_to_kind='location',
            applies_to_id='waterdeep',
            label='Waterdeep anti-enchantment norm',
            scope=NormScope.LOCATION,
            tags=(MagicalNormTag.ANTI_ENCHANTMENT,),
            summary='Charm and coercive social magic in public settings are treated as improper and alarming.',
            suspicious_magic_modifier=2,
        ),
        'norm:high-road-pragmatic': NormProfile(
            norm_id='norm:high-road-pragmatic',
            applies_to_kind='location',
            applies_to_id='high-road',
            label='High Road pragmatism',
            scope=NormScope.LOCATION,
            tags=(MagicalNormTag.OPEN_MAGIC,),
            summary='Travel magic that keeps the road moving is usually accepted.',
            helpful_magic_modifier=-1,
        ),
        'norm:triboar-trail-pragmatic': NormProfile(
            norm_id='norm:triboar-trail-pragmatic',
            applies_to_kind='location',
            applies_to_id='triboar-trail',
            label='Triboar Trail pragmatism',
            scope=NormScope.LOCATION,
            tags=(MagicalNormTag.OPEN_MAGIC,),
            summary='Remote trail travel rewards practical survival magic more than decorum.',
            helpful_magic_modifier=-1,
        ),
        'norm:phandalin-frontier': NormProfile(
            norm_id='norm:phandalin-frontier',
            applies_to_kind='location',
            applies_to_id='phandalin',
            label='Phandalin frontier norms',
            scope=NormScope.LOCATION,
            tags=(MagicalNormTag.GUARDED_MAGIC, MagicalNormTag.PUBLIC_ORDER_SENSITIVE),
            summary='Useful magic is accepted, but threats, coercion, and reckless force travel fast through town.',
            suspicious_magic_modifier=1,
            hostile_magic_modifier=2,
        ),
        'norm:lords-alliance-decorum': NormProfile(
            norm_id='norm:lords-alliance-decorum',
            applies_to_kind='faction',
            applies_to_id='lords-alliance',
            label="Lords' Alliance decorum",
            scope=NormScope.FACTION,
            tags=(MagicalNormTag.NOBLE_COURT_DECORUM, MagicalNormTag.PUBLIC_ORDER_SENSITIVE),
            summary='Order, restraint, and proper conduct matter in Alliance-facing scenes.',
            suspicious_magic_modifier=1,
            hostile_magic_modifier=2,
        ),
        'norm:watch-restricted-magic': NormProfile(
            norm_id='norm:watch-restricted-magic',
            applies_to_kind='faction',
            applies_to_id='waterdeep-watch',
            label='Watch restricted magic',
            scope=NormScope.FACTION,
            tags=(MagicalNormTag.RESTRICTED_MAGIC, MagicalNormTag.PUBLIC_ORDER_SENSITIVE),
            summary='The Watch treats public magical disturbances as civic-order concerns.',
            suspicious_magic_modifier=1,
            hostile_magic_modifier=2,
        ),
        'norm:gundren-public-secrecy': NormProfile(
            norm_id='norm:gundren-public-secrecy',
            applies_to_kind='npc',
            applies_to_id='gundren-rockseeker',
            label='Gundren public secrecy',
            scope=NormScope.NPC,
            tags=(MagicalNormTag.GUARDED_MAGIC,),
            summary='Gundren dislikes anything in public that draws attention to his business.',
            suspicious_magic_modifier=1,
        ),
        'norm:sildar-discipline': NormProfile(
            norm_id='norm:sildar-discipline',
            applies_to_kind='npc',
            applies_to_id='sildar-hallwinter',
            label='Sildar discipline',
            scope=NormScope.NPC,
            tags=(MagicalNormTag.PUBLIC_ORDER_SENSITIVE, MagicalNormTag.ANTI_PUBLIC_THREATS),
            summary='Sildar is primed to react sharply to public disorder and coercion.',
            suspicious_magic_modifier=1,
            hostile_magic_modifier=1,
        ),
    }
    location_bindings = {
        'waterdeep': LocationSocialBinding(
            location_id='waterdeep',
            label='Waterdeep',
            default_norm_ids=('norm:waterdeep-public-order', 'norm:waterdeep-anti-enchantment'),
            authority_id='waterdeep-watch',
            territory_faction_ids=('lords-alliance', 'merchant-guild'),
            scene_type_ids=('tavern_common_room', 'city_street', 'open_market', 'city_guard_checkpoint'),
        ),
        'high-road': LocationSocialBinding(
            location_id='high-road',
            label='The High Road',
            default_norm_ids=('norm:high-road-pragmatic',),
            authority_id='local-authority',
            territory_faction_ids=('caravan-company',),
            scene_type_ids=('roadside_inn', 'wilderness_campsite'),
        ),
        'triboar-trail': LocationSocialBinding(
            location_id='triboar-trail',
            label='Triboar Trail',
            default_norm_ids=('norm:triboar-trail-pragmatic',),
            authority_id='local-authority',
            territory_faction_ids=('caravan-company',),
            scene_type_ids=('wilderness_campsite',),
        ),
        'phandalin': LocationSocialBinding(
            location_id='phandalin',
            label='Phandalin',
            default_norm_ids=('norm:phandalin-frontier',),
            authority_id='town-council',
            territory_faction_ids=('merchant-guild', 'town-council'),
            scene_type_ids=('open_market', 'village_square'),
        ),
        'cragmaw-hideout': LocationSocialBinding(
            location_id='cragmaw-hideout',
            label='Cragmaw Hideout',
            default_norm_ids=(),
            authority_id=None,
            territory_faction_ids=(),
            scene_type_ids=('wilderness_campsite',),
        ),
    }
    scene_bindings = {
        'scene-waterdeep-gundren-briefing': SceneSocialBinding(
            scene_id='scene-waterdeep-gundren-briefing',
            location_id='waterdeep',
            scene_type_id='tavern_common_room',
            norm_ids=('norm:scene:tavern-common-room',),
            faction_ids=('rockseeker', 'lords-alliance', 'waterdeep-watch'),
            witness_archetype_overrides={
                'gundren-rockseeker': 'merchant',
                'sildar-hallwinter': 'watch_officer',
            },
        ),
        'scene-00-high-road-journey': SceneSocialBinding(
            scene_id='scene-00-high-road-journey',
            location_id='high-road',
            scene_type_id='wilderness_campsite',
            norm_ids=('norm:scene:wilderness-campsite',),
            faction_ids=('caravan-company', 'rockseeker'),
            witness_archetype_overrides={
                'gundren-rockseeker': 'merchant',
                'sildar-hallwinter': 'watch_officer',
            },
        ),
    }
    consequence_templates = {
        'consequence:helpful-public-magic': IncidentConsequenceTemplate(
            template_id='consequence:helpful-public-magic',
            label='Helpful public magic',
            incident_categories=(SocialIncidentCategory.AID_OR_HEALING,),
            reaction_categories=(WitnessReactionCategory.IGNORE, WitnessReactionCategory.CURIOUS),
            required_norm_tags=(MagicalNormTag.PUBLIC_ORDER_SENSITIVE,),
            party_summary='The public magic reads as helpful rather than threatening.',
            dm_summary='Helpful public magic may become a favorable rumor instead of a problem.',
            propagation_chain_ids=('chain:local-rumor',),
        ),
        'consequence:suspicious-public-magic': IncidentConsequenceTemplate(
            template_id='consequence:suspicious-public-magic',
            label='Suspicious public magic',
            incident_categories=(SocialIncidentCategory.WITNESSED_SPELLCASTING, SocialIncidentCategory.SUSPICIOUS_SPELLCASTING, SocialIncidentCategory.UNAUTHORIZED_MAGIC),
            reaction_categories=(WitnessReactionCategory.SUSPICIOUS, WitnessReactionCategory.ALARMED, WitnessReactionCategory.REPORT_TO_AUTHORITY),
            required_norm_tags=(MagicalNormTag.GUARDED_MAGIC,),
            relationship_tags=('watchful',),
            party_summary='The witnesses read the magic as questionable, and the room grows more careful around the party.',
            dm_summary='Suspicious public magic should raise scrutiny and often seeds later reports.',
            open_loop='Witnesses may remember the spellcasting as improper.',
            propagation_chain_ids=('chain:authority-report', 'chain:faction-notice'),
        ),
        'consequence:guarded-enchantment': IncidentConsequenceTemplate(
            template_id='consequence:guarded-enchantment',
            label='Guarded enchantment or coercive casting',
            incident_categories=(SocialIncidentCategory.SUSPICIOUS_SPELLCASTING, SocialIncidentCategory.ENCHANTMENT_MAGIC_USED, SocialIncidentCategory.UNAUTHORIZED_MAGIC),
            reaction_categories=(WitnessReactionCategory.SUSPICIOUS, WitnessReactionCategory.ALARMED, WitnessReactionCategory.REPORT_TO_AUTHORITY),
            required_norm_tags=(MagicalNormTag.ANTI_ENCHANTMENT,),
            relationship_tags=('coercion-remembered',),
            faction_tags=('decorum-breach',),
            authority_tags=('magical-scrutiny',),
            party_summary='The casting reads as coercive in this setting, and trust in the room drops.',
            dm_summary='Anti-enchantment norms turn otherwise subtle magic into a serious social violation.',
            open_loop='Authority-minded witnesses may frame the party as manipulative.',
            propagation_chain_ids=('chain:watch-alert', 'chain:faction-notice'),
        ),
        'consequence:hostile-public-magic': IncidentConsequenceTemplate(
            template_id='consequence:hostile-public-magic',
            label='Hostile public magic or violence',
            incident_categories=(SocialIncidentCategory.HOSTILE_SPELLCASTING, SocialIncidentCategory.VIOLENCE),
            reaction_categories=(WitnessReactionCategory.ALARMED, WitnessReactionCategory.CONFRONTATIONAL, WitnessReactionCategory.HOSTILE, WitnessReactionCategory.ESCALATE_TO_COMBAT_CANDIDATE),
            required_norm_tags=(MagicalNormTag.PUBLIC_ORDER_SENSITIVE,),
            relationship_tags=('dangerous',),
            authority_tags=('public-disturbance',),
            party_summary='The violence shocks the room and puts the party under immediate social pressure.',
            dm_summary='Hostile public magic should create authority attention, fear, and strong witness memory.',
            open_loop='Public violence may bring official consequences even if the fight ends quickly.',
            propagation_chain_ids=('chain:watch-alert', 'chain:authority-report'),
        ),
        'consequence:public-threat-against-employer': IncidentConsequenceTemplate(
            template_id='consequence:public-threat-against-employer',
            label='Public threat against an employer figure',
            incident_categories=(SocialIncidentCategory.THREAT, SocialIncidentCategory.INTIMIDATION),
            scene_ids=('scene-waterdeep-gundren-briefing',),
            witness_archetype_ids=('merchant', 'guild_member'),
            relationship_tags=('contract-risk',),
            faction_tags=('employer-memory',),
            party_summary='Threatening an employer in public strains the bargain immediately.',
            dm_summary='Gundren-style employer figures should remember public threats and reconsider trust fast.',
            open_loop='The current employer may revoke trust or warn others about the party.',
            propagation_chain_ids=('chain:employer-blacklist',),
        ),
        'consequence:merchant-theft': IncidentConsequenceTemplate(
            template_id='consequence:merchant-theft',
            label='Theft seen by merchant witnesses',
            incident_categories=(SocialIncidentCategory.THEFT,),
            witness_archetype_ids=('merchant', 'barkeep'),
            relationship_tags=('service-refusal-risk',),
            faction_tags=('theft-memory',),
            party_summary='The theft marks the party as untrustworthy in trade-facing circles.',
            dm_summary='Merchant or barkeep witnesses should turn theft into refusal-of-service and rumor risk.',
            propagation_chain_ids=('chain:merchant-refusal', 'chain:local-rumor'),
        ),
    }
    propagation_chains = {
        'chain:local-rumor': PropagationChainTemplate(
            chain_id='chain:local-rumor',
            label='Local rumor chain',
            trigger_incident_categories=(SocialIncidentCategory.AID_OR_HEALING, SocialIncidentCategory.WITNESSED_SPELLCASTING, SocialIncidentCategory.THREAT, SocialIncidentCategory.THEFT),
            propagation_kind=SocialPropagationKind.LOCAL_RUMOR,
            target_mode='location',
            delay_seconds=30 * 60,
            public_visible=True,
            summary_template='Word of the incident begins to circulate around {target_label}.',
        ),
        'chain:authority-report': PropagationChainTemplate(
            chain_id='chain:authority-report',
            label='Authority report chain',
            trigger_incident_categories=(SocialIncidentCategory.SUSPICIOUS_SPELLCASTING, SocialIncidentCategory.HOSTILE_SPELLCASTING, SocialIncidentCategory.VIOLENCE, SocialIncidentCategory.THREAT, SocialIncidentCategory.UNAUTHORIZED_MAGIC),
            reaction_categories=(WitnessReactionCategory.ALARMED, WitnessReactionCategory.REPORT_TO_AUTHORITY, WitnessReactionCategory.CONFRONTATIONAL, WitnessReactionCategory.HOSTILE, WitnessReactionCategory.ESCALATE_TO_COMBAT_CANDIDATE),
            propagation_kind=SocialPropagationKind.AUTHORITY_REPORT,
            target_mode='location_authority',
            delay_seconds=5 * 60,
            public_visible=False,
            summary_template='{witness_label} may report the incident to {target_label}.',
            social_tags=('legal-scrutiny',),
        ),
        'chain:faction-notice': PropagationChainTemplate(
            chain_id='chain:faction-notice',
            label='Faction notice chain',
            trigger_incident_categories=(SocialIncidentCategory.SUSPICIOUS_SPELLCASTING, SocialIncidentCategory.HOSTILE_SPELLCASTING, SocialIncidentCategory.AID_OR_HEALING, SocialIncidentCategory.THREAT),
            propagation_kind=SocialPropagationKind.FACTION_PROPAGATION,
            target_mode='witness_factions',
            delay_seconds=15 * 60,
            public_visible=False,
            summary_template='{witness_label} may spread word of the incident within {target_label}.',
        ),
        'chain:employer-blacklist': PropagationChainTemplate(
            chain_id='chain:employer-blacklist',
            label='Employer blacklist chain',
            trigger_incident_categories=(SocialIncidentCategory.THREAT, SocialIncidentCategory.CONTRACT_BROKEN),
            propagation_kind=SocialPropagationKind.FACTION_PROPAGATION,
            target_mode='specific_faction',
            target_id='rockseeker',
            delay_seconds=20 * 60,
            public_visible=False,
            summary_template='Rockseeker interests may reconsider trusting the party with future work.',
            social_tags=('blacklist-risk',),
        ),
        'chain:merchant-refusal': PropagationChainTemplate(
            chain_id='chain:merchant-refusal',
            label='Merchant refusal chain',
            trigger_incident_categories=(SocialIncidentCategory.THEFT, SocialIncidentCategory.CONTRACT_BROKEN),
            propagation_kind=SocialPropagationKind.FACTION_PROPAGATION,
            target_mode='specific_faction',
            target_id='merchant-guild',
            delay_seconds=30 * 60,
            public_visible=False,
            summary_template='Merchants may quietly stop offering the party easy credit or service.',
            social_tags=('service-refusal-risk',),
        ),
        'chain:watch-alert': PropagationChainTemplate(
            chain_id='chain:watch-alert',
            label='Watch alert chain',
            trigger_incident_categories=(SocialIncidentCategory.HOSTILE_SPELLCASTING, SocialIncidentCategory.VIOLENCE, SocialIncidentCategory.ENCHANTMENT_MAGIC_USED),
            propagation_kind=SocialPropagationKind.AUTHORITY_REPORT,
            target_mode='specific_faction',
            target_id='waterdeep-watch',
            delay_seconds=2 * 60,
            public_visible=False,
            summary_template='The Waterdeep Watch is likely to hear about the disturbance soon.',
            social_tags=('watch-alert',),
        ),
    }
    location_labels = {binding.location_id: binding.label for binding in location_bindings.values()}
    location_labels.setdefault('phandalin', 'Phandalin')
    faction_labels = {template_id: template.label for template_id, template in faction_templates.items()}
    faction_labels.setdefault('local-authority', 'Local authorities')
    authority_by_location = {
        location_id: binding.authority_id
        for location_id, binding in location_bindings.items()
        if binding.authority_id is not None
    }
    npc_factions = {npc_id: template.faction_ids for npc_id, template in npc_templates.items()}
    return CampaignSocialContentPack(
        campaign_id='lmop',
        location_labels=location_labels,
        faction_labels=faction_labels,
        npc_factions=npc_factions,
        authority_by_location=authority_by_location,
        norm_profiles=norm_profiles,
        witness_archetypes=witness_archetypes,
        faction_templates=faction_templates,
        npc_templates=npc_templates,
        consequence_templates=consequence_templates,
        propagation_chains=propagation_chains,
        location_bindings=location_bindings,
        scene_bindings=scene_bindings,
    )
